const data = {
	categories: [
		"Compacts",
		"Coupes",
		"Sports",
		"Sports Classics",
		"Super",
		"Muscle",
		"Offroad",
		"SUV",
		"Vans",
		"Sedans",
		"Motorcycles",
	],
	vehicles: [
		[
			{ model: "blista" },
			{ model: "brioso" },
			{ model: "dilettante" },
			{ model: "issi2" },
			{ model: "panto" },
			{ model: "prairie" },
			{ model: "rhapsody" },
			{ model: "issi3" }
		],
		[
			{ model: "cogcabrio" },
			{ model: "exemplar" },
			{ model: "f620" },
			{ model: "felon" },
			{ model: "felon2" },
			{ model: "jackal" },
			{ model: "oracle" },
			{ model: "oracle2" },
			{ model: "sentinel" },
			{ model: "sentinel2" },
			{ model: "windsor" },
			{ model: "windsor2" },
			{ model: "zion" },
			{ model: "zion2" }
		],
		[
			{ model: "ninef" },
			{ model: "ninef2" },
			{ model: "alpha" },
			{ model: "banshee" },
			{ model: "banshee2" },
			{ model: "bestiagts" },
			{ model: "buffalo" },
			{ model: "buffalo2" },
			{ model: "carbonizzare" },
			{ model: "raiden" },
			{ model: "comet2" },
			{ model: "comet3" },
			{ model: "comet4" },
			{ model: "comet5" },
			{ model: "coquette" },
			{ model: "tampa2" },
			{ model: "hotring" },
			{ model: "elegy2" },
			{ model: "elegy" },
			{ model: "feltzer2" },
			{ model: "furoregt" },
			{ model: "fusilade" },
			{ model: "futo" },
			{ model: "blista3" },
			{ model: "jester" },
			{ model: "jester2" },
			{ model: "khamelion" },
			{ model: "kuruma" },
			{ model: "kuruma2" },
			{ model: "lynx" },
			{ model: "massacro" },
			{ model: "massacro2" },
			{ model: "neon" },
			{ model: "omnis" },
			{ model: "pariah" },
			{ model: "penumbra" },
			{ model: "rapidgt" },
			{ model: "rapidgt2" },
			{ model: "raptor" },
			{ model: "revolter" },
			{ model: "ruston" },
			{ model: "schafter2" },
			{ model: "schafter3" },
			{ model: "sentinel3" },
			{ model: "seven70" },
			{ model: "specter" },
			{ model: "specter2" },
			{ model: "buffalo3" },
			{ model: "streiter" },
			{ model: "sultan" },
			{ model: "sultanrs" },
			{ model: "surano" },
			{ model: "tropos" },
			{ model: "verlierer2" }
		],
		[
			{ model: "ardent" },
			{ model: "casco" },
			{ model: "cheetah2" },
			{ model: "coquette2" },
			{ model: "btype2" },
			{ model: "gt500" },
			{ model: "infernus2" },
			{ model: "jester3" },
			{ model: "jb700" },
			{ model: "z190" },
			{ model: "mamba" },
			{ model: "manana" },
			{ model: "monroe" },
			{ model: "peyote" },
			{ model: "pigalle" },
			{ model: "rapidgt3" },
			{ model: "retinue" },
			{ model: "btype" },
			{ model: "btype3" },
			{ model: "savestra" },
			{ model: "stinger" },
			{ model: "stingergt" },
			{ model: "feltzer3" },
			{ model: "torero" },
			{ model: "tornado" },
			{ model: "tornado3" },
			{ model: "tornado4" },
			{ model: "tornado5" },
			{ model: "tornado6" },
			{ model: "turismo2" },
			{ model: "viseris" },
			{ model: "ztype" },
			{ model: "stafford" }
		],
		[
			{ model: "pfister811" },
			{ model: "adder" },
			{ model: "bullet" },
			{ model: "cheetah" },
			{ model: "cyclone" },
			{ model: "entityxf" },
			{ model: "sheava" },
			{ model: "fmj" },
			{ model: "gp1" },
			{ model: "infernus" },
			{ model: "italigtb" },
			{ model: "italigtb2" },
			{ model: "nero" },
			{ model: "nero2" },
			{ model: "osiris" },
			{ model: "autarch" },
			{ model: "penetrator" },
			{ model: "le7b" },
			{ model: "reaper" },
			{ model: "sc1" },
			{ model: "t20" },
			{ model: "tempesta" },
			{ model: "turismor" },
			{ model: "tyrus" },
			{ model: "vacca" },
			{ model: "vagner" },
			{ model: "visione" },
			{ model: "voltic" },
			{ model: "xa21" },
			{ model: "prototipo" },
			{ model: "zentorno" },
			{ model: "taipan" },
			{ model: "entity2" }
		],
		[
			{ model: "blade" },
			{ model: "buccaneer" },
			{ model: "buccaneer2" },
			{ model: "stallion2" },
			{ model: "chino" },
			{ model: "chino2" },
			{ model: "coquette3" },
			{ model: "dominator" },
			{ model: "dominator3" },
			{ model: "dukes" },
			{ model: "dukes2" },
			{ model: "gauntlet" },
			{ model: "hermes" },
			{ model: "hotknife" },
			{ model: "hustler" },
			{ model: "faction" },
			{ model: "faction2" },
			{ model: "faction3" },
			{ model: "slamvan2" },
			{ model: "lurcher" },
			{ model: "moonbeam" },
			{ model: "moonbeam2" },
			{ model: "nightshade" },
			{ model: "phoenix" },
			{ model: "picador" },
			{ model: "dominator2" },
			{ model: "ratloader" },
			{ model: "ratloader2" },
			{ model: "gauntlet2" },
			{ model: "ruiner" },
			{ model: "ruiner2" },
			{ model: "sabregt" },
			{ model: "sabregt2" },
			{ model: "slamvan" },
			{ model: "slamvan3" },
			{ model: "stallion" },
			{ model: "tampa" },
			{ model: "virgo" },
			{ model: "virgo2" },
			{ model: "virgo3" },
			{ model: "vigero" },
			{ model: "voodoo2" },
			{ model: "voodoo" },
			{ model: "yosemite" },
		],
		[
			{ model: "bifta" },
			{ model: "bodhi2" },
			{ model: "brawler" },
			{ model: "kamacho" },
			{ model: "trophytruck2" },
			{ model: "dubsta3" },
			{ model: "dune" },
			{ model: "dloader" },
			{ model: "bfinjection" },
			{ model: "kalahari" },
			{ model: "mesa3" },
			{ model: "nightshark" },
			{ model: "rancherxl" },
			{ model: "riata" },
			{ model: "rebel2" },
			{ model: "rebel" },
			{ model: "sandking2" },
			{ model: "sandking" },
			{ model: "trophytruck" }
		],
		[
			{ model: "baller" },
			{ model: "baller2" },
			{ model: "baller3" },
			{ model: "baller4" },
			{ model: "bjxl" },
			{ model: "cavalcade" },
			{ model: "cavalcade2" },
			{ model: "contender" },
			{ model: "dubsta2" },
			{ model: "fq2" },
			{ model: "granger" },
			{ model: "gresley" },
			{ model: "habanero" },
			{ model: "huntley" },
			{ model: "landstalker" },
			{ model: "mesa" },
			{ model: "patriot" },
			{ model: "radi" },
			{ model: "rocoto" },
			{ model: "seminole" },
			{ model: "serrano" },
			{ model: "xls" }
		],
		[
			{ model: "bison" },
			{ model: "bobcatxl" },
			{ model: "burrito3" },
			{ model: "camper" },
			{ model: "gburrito2" },
			{ model: "journey" },
			{ model: "minivan" },
			{ model: "minivan2" },
			{ model: "paradise" },
			{ model: "rumpo" },
			{ model: "rumpo3" },
			{ model: "surfer" },
			{ model: "surfer2" },
			{ model: "youga" },
			{ model: "youga2" },
			{ model: "pounder2" },
			{ model: "benson" },
			{ model: "mule2" },
			{ model: "speedo" }
		],
		[
			{ model: "asea" },
			{ model: "asterope" },
			{ model: "cognoscenti" },
			{ model: "cog55" },
			{ model: "emperor" },
			{ model: "emperor2" },
			{ model: "fugitive" },
			{ model: "glendale" },
			{ model: "ingot" },
			{ model: "intruder" },
			{ model: "premier" },
			{ model: "primo" },
			{ model: "primo2" },
			{ model: "regina" },
			{ model: "romero" },
			{ model: "schafter2" },
			{ model: "stanier" },
			{ model: "stratum" },
			{ model: "stretch" },
			{ model: "superd" },
			{ model: "surge" },
			{ model: "tailgater" },
			{ model: "warrener" },
			{ model: "washington" }
		],
		[
			{ model: "akuma" },
			{ model: "avarus" },
			{ model: "bagger" },
			{ model: "bati" },
			{ model: "bati2" },
			{ model: "bf400" },
			{ model: "carbonrs" },
			{ model: "cliffhanger" },
			{ model: "daemon2" },
			{ model: "daemon" },
			{ model: "defiler" },
			{ model: "diablous" },
			{ model: "diablous2" },
			{ model: "double" },
			{ model: "enduro" },
			{ model: "esskey" },
			{ model: "faggio2" },
			{ model: "faggio" },
			{ model: "faggio3" },
			{ model: "fcr2" },
			{ model: "gargoyle" },
			{ model: "hakuchou" },
			{ model: "hakuchou2" },
			{ model: "hexer" },
			{ model: "innovation" },
			{ model: "lectro" },
			{ model: "manchez" },
			{ model: "nemesis" },
			{ model: "nightblade" },
			{ model: "pcj" },
			{ model: "ratbike" },
			{ model: "ruffian" },
			{ model: "sanchez" },
			{ model: "Sanctus" },
			{ model: "sovereign" },
			{ model: "thrust" },
			{ model: "vader" },
			{ model: "vindicator" },
			{ model: "vortex" },
			{ model: "wolfsbane" },
			{ model: "zombiea" },
			{ model: "zombieb" }
		]
	]
}

export { data };